// <auto-generated />
using System;
using AuthenLearn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthenLearn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730100523_DebtTable_2")]
    partial class DebtTable_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthenLearn.Model.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmountOfDebt")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("AuthenLearn.Model.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc580c44-2332-4457-99c9-5ea4c096690a"),
                            Amount = 1000000.0,
                            Date = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "tiền lương tháng 7",
                            Type = 0,
                            UserId = new Guid("4090476f-2e7e-4884-9eca-08ddc9cc4038")
                        });
                });

            modelBuilder.Entity("AuthenLearn.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("AuthenLearn.Model.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("user_account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc880c44-2632-4457-99c9-5ea4c096690a"),
                            Password = "Admin123",
                            RoleId = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("84057361-30b5-4840-a71b-28d951cc0653"),
                            Password = "User123",
                            RoleId = 2,
                            UserName = "User"
                        });
                });

            modelBuilder.Entity("AuthenLearn.Model.Debt", b =>
                {
                    b.HasOne("AuthenLearn.Model.UserAccount", "UserAccount")
                        .WithMany("Debts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("AuthenLearn.Model.Expense", b =>
                {
                    b.HasOne("AuthenLearn.Model.Debt", "Debt")
                        .WithMany("Expenses")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthenLearn.Model.UserAccount", "UserAccount")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Debt");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("AuthenLearn.Model.UserAccount", b =>
                {
                    b.HasOne("AuthenLearn.Model.Role", "Role")
                        .WithMany("UserAccount")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AuthenLearn.Model.Debt", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("AuthenLearn.Model.Role", b =>
                {
                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("AuthenLearn.Model.UserAccount", b =>
                {
                    b.Navigation("Debts");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
